# Generated by Django 3.0.4 on 2020-08-21 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q1', models.TextField()),
                ('Q2', models.TextField()),
                ('Q3', models.TextField()),
                ('Q4', models.TextField()),
                ('Q5', models.TextField()),
                ('Q6', models.TextField()),
                ('Q7', models.TextField()),
                ('Q8', models.TextField()),
                ('Q9', models.TextField()),
                ('Q10', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
