# Generated by Django 3.0.4 on 2020-08-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='author',
        ),
        migrations.AddField(
            model_name='questions',
            name='Deptartment',
            field=models.CharField(default='r', max_length=50),
        ),
        migrations.AddField(
            model_name='questions',
            name='Name',
            field=models.CharField(default='cs', max_length=50),
        ),
        migrations.AddField(
            model_name='questions',
            name='contact_num',
            field=models.CharField(default='r', max_length=50),
        ),
    ]
