# Generated by Django 3.0.4 on 2020-08-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20200821_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='Deptartment',
            field=models.CharField(default='--', max_length=50),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Name',
            field=models.CharField(default='--', max_length=50),
        ),
        migrations.AlterField(
            model_name='questions',
            name='contact_num',
            field=models.CharField(default='--', max_length=50),
        ),
    ]
