# Generated by Django 3.0.4 on 2020-08-22 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20200821_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='Q1',
            field=models.TextField(default='--'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Q10',
            field=models.TextField(default='--'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Q2',
            field=models.TextField(default='--'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Q3',
            field=models.TextField(default='--'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Q4',
            field=models.TextField(default='--'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Q5',
            field=models.TextField(default='--'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Q6',
            field=models.TextField(default='--'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Q7',
            field=models.TextField(default='--'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Q8',
            field=models.TextField(default='--'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Q9',
            field=models.TextField(default='--'),
        ),
    ]
